version: '3.9'

services:
  database:
    image: postgres
    container_name: invoices_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: invoices_db
    ports:
      - 5433:5432